version: "3.6"

services:

  timeseriesdb:
    container_name: timeseriesdb
    build:
      context: influxdb
    ports:
      - 8086:8086
    volumes:
      - ./influxdb/data/influxdb:/var/lib/influxdb \
      - ./influxdb/data/influxdb2:/var/lib/influxdb2 \
    #restart: always
