version: "3.6"

services:

  influxdb:
    image: influxdb:2.5.1-alpine
    volumes:
      - ./influxdb/data/svl/influxdb2:/var/lib/influxdb2:rw
    env_file:
      - ./influxdb/.env
    ports:
      - 8086:8086
    restart: on-failure

  alphavantage_scraper:
    container_name: alphavantage_scraper
    build:
      context: ./alphavantage_scraper
      dockerfile: Dockerfile
    env_file:
      - ./alphavantage_scraper/.env
    depends_on:
      - influxdb

  dash_app:
    container_name: dash_app
    build:
      context: ./dash_app
      dockerfile: Dockerfile
    env_file:
      - ./dash_app/.env
    ports:
      - 8080:8080
    depends_on:
      - influxdb

  # blobstorage:
  #   image: minio/minio:RELEASE.2022-11-17T23-20-09Z.fips
  #   #volumes:
  #   #  - ./blobstore/data:/
  #   env_file:
  #     - ./blobstore/.env
  #   ports:
  #     - 9000:9000
  #   restart: on-failure

volumes:
  influxdb2: