version: "3.6"

services:

  influxdb:
    image: influxdb:2.5.1-alpine
    volumes:
      - ./influxdb/data/svl/influxdb2:/var/lib/influxdb2:rw
    env_file:
      - ./influxdb/.env
    ports:
      - 8086:8086
    restart: on-failure

  alphavantage_scraper:
    container_name: alphavantage_scraper
    build:
      context: ./alphavantage_scraper
      dockerfile: Dockerfile
    env_file:
      - ./alphavantage_scraper/.env
    depends_on:
      - influxdb

volumes:
  influxdb2: